// Code generated by MockGen. DO NOT EDIT.
// Source: ./exchange.go
//
// Generated by this command:
//
//	mockgen -source ./exchange.go -destination ./exchange_mock_test.go -package httpcontroller_test
//

// Package httpcontroller_test is a generated GoMock package.
package httpcontroller_test

import (
	context "context"
	reflect "reflect"

	services "github.com/DIMO-Network/dauth/internal/exchange/services"
	access "github.com/DIMO-Network/dauth/internal/exchange/services/access"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenSigner is a mock of TokenSigner interface.
type MockTokenSigner struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSignerMockRecorder
	isgomock struct{}
}

// MockTokenSignerMockRecorder is the mock recorder for MockTokenSigner.
type MockTokenSignerMockRecorder struct {
	mock *MockTokenSigner
}

// NewMockTokenSigner creates a new mock instance.
func NewMockTokenSigner(ctrl *gomock.Controller) *MockTokenSigner {
	mock := &MockTokenSigner{ctrl: ctrl}
	mock.recorder = &MockTokenSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSigner) EXPECT() *MockTokenSignerMockRecorder {
	return m.recorder
}

// SignPrivilegePayload mocks base method.
func (m *MockTokenSigner) SignPrivilegePayload(ctx context.Context, req services.PrivilegeTokenDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignPrivilegePayload", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignPrivilegePayload indicates an expected call of SignPrivilegePayload.
func (mr *MockTokenSignerMockRecorder) SignPrivilegePayload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignPrivilegePayload", reflect.TypeOf((*MockTokenSigner)(nil).SignPrivilegePayload), ctx, req)
}

// MockAccessService is a mock of AccessService interface.
type MockAccessService struct {
	ctrl     *gomock.Controller
	recorder *MockAccessServiceMockRecorder
	isgomock struct{}
}

// MockAccessServiceMockRecorder is the mock recorder for MockAccessService.
type MockAccessServiceMockRecorder struct {
	mock *MockAccessService
}

// NewMockAccessService creates a new mock instance.
func NewMockAccessService(ctrl *gomock.Controller) *MockAccessService {
	mock := &MockAccessService{ctrl: ctrl}
	mock.recorder = &MockAccessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessService) EXPECT() *MockAccessServiceMockRecorder {
	return m.recorder
}

// ValidateAccess mocks base method.
func (m *MockAccessService) ValidateAccess(ctx context.Context, req *access.AccessRequest, ethAddr common.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccess", ctx, req, ethAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAccess indicates an expected call of ValidateAccess.
func (mr *MockAccessServiceMockRecorder) ValidateAccess(ctx, req, ethAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccess", reflect.TypeOf((*MockAccessService)(nil).ValidateAccess), ctx, req, ethAddr)
}
