name: Build
on:
  pull_request:
    branches: ["**"]
  push:
    branches:
      - main

jobs:
  build-test:
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
